### PR TITLE
Bj employeedetails

### PR DESCRIPTION
**Pull request by brantleyjones74**
# Description

When user clicks on details on the employees page then that employee's full name, department, currently assigned computer, and list of training programs user is signed up for should be displayed.

Related to Issue #  3

# Testing Instructions

Click Employees up top then click on details next to employees to make sure data is displayed correctly.

# Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings or errors
- [x] I have added test instructions that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by sarahkfleming — APPROVED** [review]
Everything works! 💯 🥇

**Review by kellycoles — APPROVED** [review]
👍 looks great

**Review by bobbybrady — APPROVED** [review]
🎈🎆🎈🎆🎆🎈🧨🎇🎉🎃

**Comment by kellycoles** [comment]
🥇

**Pull request merged**
